### ISSUE TITLE
CMD [ "yarn", "start:prod" ]

### ISSUE THREAD

**Issue by RuslanGlaznyov** [js-procamp/distributed-node#3]
https://github.com/js-procamp/distributed-node/blob/446ed60e0818f40b601685fe84f1d5c4e6214a08/user-service/Dockerfile#L22

May be better to run with command `CMD ["node","index.js"]` instead of `CMD [ "yarn", "start:prod" ]`

nodejs docker best practice: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md

**Comment by inna-i** [comment]
Both approaches can be used. If you would like to run with Node, it should be like -
`CMD  ["node", "dist/main.js"]`
